[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.solc]
remappings = [
  "@aave-v3-origin=lib/aave-v3-origin/src",
  "@aave-address-book=lib/aave-address-book/src/core/contracts",
  "@openzeppelin=lib/openzeppelin-solidity",
]

[profile.release]
optimizer = true
optimizer_runs = 200
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
